name: Publish friendly-id

on:
  push:
    tags:
      - "*"
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI


jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # version: "0.7.4"  # default to latest
          # python-version: 3.13
          enable-cache: true
      - name: Build package
        run: make
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
