name: test friendly-id

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "friendly_id/**"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/workflows/test.yml"
      - "friendly_id/**"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # version: "0.7.4"  # default to latest
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # version: "0.7.4"  # default to latest
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Test
        run: make test
